### ISSUE TITLE
problem accessing distingEX_tools/dex_preset_editor.html

### ISSUE THREAD

**Issue by zef18** [expertsleepersltd/distingEX_tools#1]
Impossible to display anything when trying to open dex_preset_editor.html , on the other hand everything works fine when executing dex_screenshot_tool.html.
I use Google Chrome and local files.
Please Help

**Comment by expertsleepers** [comment]
What do you mean by "Impossible to display anything"? A screenshot may help.

**Comment by zef18** [comment]
Hello, thanks for your answer, everything works now, it's a question of
updating, from 1.5 to 1.8
Regards
Zef18

Le jeu. 24 juin 2021 à 18:07, Andrew Ostler ***@***.***> a
écrit :
